"""add rag knowledge tables

Revision ID: 28190fa73066
Revises: 
Create Date: 2026-09-22 20:55:40.689459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '28190fa73066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_documents_branch_id'), 'ai_knowledge_documents', ['branch_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_id'), 'ai_knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_knowledge_id'), 'ai_knowledge_documents', ['knowledge_id'], unique=True)
    op.create_table('ai_knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_chunks_document_id'), 'ai_knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_chunks_id'), 'ai_knowledge_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_knowledge_chunks_id'), table_name='ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_chunks_document_id'), table_name='ai_knowledge_chunks')
    op.drop_table('ai_knowledge_chunks')
    op.drop_index(op.f('ix_ai_knowledge_documents_knowledge_id'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_id'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_branch_id'), table_name='ai_knowledge_documents')
    op.drop_table('ai_knowledge_documents')
    # ### end Alembic commands ###
